using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Strings;
using Mutagen.Bethesda.Synthesis;
using Noggog;
using System;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using MetricUnits.Util;

namespace MetricUnits
{
    public class Program
    {
        private static Lazy<Settings> _lazySettings = null!;
        private static Settings Settings => _lazySettings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "Ordinator - Metric Units Patch.esp")
                .SetAutogeneratedSettings("Settings", "settings.json", out _lazySettings)
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Console.WriteLine("Initialization Complete");

            if (Settings.keys.Count == 0)
            {
                Console.WriteLine($"[ERROR]:  The plugin list is empty! (See the settings tab to add plugins)");
                return;
            }

            ulong count = 0;

            Regex regex = new("<([0-9.-]+)>\\s(\\w+)", RegexOptions.Singleline);


            int tmpcount = 0;
            foreach(var plugin in state.LoadOrder.ListedOrder)
            {
                Console.WriteLine($"[{tmpcount++}]:\t {plugin.ModKey}");
            }

            foreach (var mgef in state.LoadOrder.PriorityOrder.MagicEffect().WinningContextOverrides())
            {
                if (!Settings.Whitelisted(mgef) || mgef.Record.EditorID == null || mgef.Record.Description == null || !mgef.Record.Description.Any())
                    continue;

                var copy = mgef.Record.DeepCopy()!;

                ulong copyCount = count;
                // replace all regex matches with the string determined by the delegate
                var str = regex.Replace(copy.Description!.Lookup(Language.English) ?? "", delegate(Match m)
                {
                    Unit.ID unit = Unit.FromString(m.Groups[2].Value);
                   
                    if (unit != Unit.ID.FEET)
                        return m.Groups[0].Value;

                    if (!m.Groups[1].Value.All(ch => Utilities.isnumchar(ch)))
                        return m.Groups[0].Value;

                    double n = Convert.ToDouble(m.Groups[1].Value);
                    double? result = Unit.Convert(n, unit, Unit.ID.METERS);

                    if (result == null)
                        return m.Groups[0].Value;

                    string s = $"<{result}> meter{(result.EqualsWithin(1.0) ? "" : "s")}";

                    Console.WriteLine($"[{++count}]\tAdding override \"{s}\" for \"{m.Groups[0].Value}\" in record: {mgef.Record.EditorID}");
                    
                    return s;
                });

                if (count == copyCount)
                    continue;

                copy.Description = str;

                Console.WriteLine(str);

                // else copy back into output patch
                state.PatchMod.MagicEffects.Set(copy);
            }
            

            Console.WriteLine($"Complete. Patched {count} record{(count == 0 || count > 1 ? "s" : "")}.");
        }
    }
}
